quarkus:
  hibernate-orm:
    database:
        generation: drop-and-create
  datasource:
    username: root
    password: root
    jdbc:
      url: jdbc:mysql://localhost:3306/prueba?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      driver: com.mysql.cj.jdbc.Driver
  rest-client:
    post-proxy:
      url: https://gorest.co.in/public/v2/
mp:
  jwt:
    verify:
      issuer: byte-company
      publickey:
        location: publickey.pem
